import {
  CalendarEvent,
  CollegeClass,
  UnavailableBlock,
  Goal,
  WeeklyTarget,
  DailyTask,
  FreeTimeAllocation,
  SemesterInfo,
  UserProfile,
} from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Aryan Sharma',
  email: 'aryan.cs24@nitc.edu',
  degree: 'B.Tech in Computer Science & Engineering',
  year: '2nd Year',
  semester: 'Semester 3',
};

export const INITIAL_SEMESTER_INFO: SemesterInfo = {
  name: 'Semester 3 (Fall 2026)',
  college: 'National Institute of Technology',
  branch: 'Computer Science and Engineering',
  startDate: '2026-08-17',
  endDate: '2026-12-18',
  calendarFileName: undefined,
  timetableFileName: undefined,
  isSetupComplete: true,
};

export const INITIAL_CLASSES: CollegeClass[] = [];

export const INITIAL_UNAVAILABLE_BLOCKS: UnavailableBlock[] = [
  {
    id: 'un-1',
    title: 'Night Sleep',
    category: 'Sleep',
    isRecurring: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startTime: '23:30',
    endTime: '07:00',
    durationMinutes: 450,
  },
  {
    id: 'un-2',
    title: 'Morning Routine & Breakfast',
    category: 'Meals',
    isRecurring: true,
    daysOfWeek: [1, 2, 3, 4, 5],
    startTime: '07:30',
    endTime: '08:30',
    durationMinutes: 60,
  },
  {
    id: 'un-3',
    title: 'College Mess Lunch',
    category: 'Meals',
    isRecurring: true,
    daysOfWeek: [1, 2, 3, 4, 5],
    startTime: '12:30',
    endTime: '13:30',
    durationMinutes: 60,
  },
  {
    id: 'un-4',
    title: 'Gym & Physical Fitness',
    category: 'Gym',
    isRecurring: true,
    daysOfWeek: [1, 2, 3, 4, 5],
    startTime: '17:00',
    endTime: '18:00',
    durationMinutes: 60,
  },
  {
    id: 'un-5',
    title: 'Hostel Dinner & Relax',
    category: 'Meals',
    isRecurring: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startTime: '20:15',
    endTime: '21:00',
    durationMinutes: 45,
  },
  {
    id: 'un-6',
    title: 'Weekly Family Video Call',
    category: 'Family/personal',
    isRecurring: true,
    daysOfWeek: [0], // Sunday
    startTime: '10:00',
    endTime: '11:30',
    durationMinutes: 90,
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'g-1',
    title: 'GATE 2028 (Computer Science)',
    targetDate: '2028-02-05',
    weeklyTargetHours: 10,
    priority: 'High',
    description: 'Targeting top 100 AIR for PSU & IISc M.Tech. Focused on Core CS fundamentals and Mathematics.',
    category: 'GATE',
  },
  {
    id: 'g-2',
    title: 'Software Engineering Placements',
    targetDate: '2027-08-15',
    weeklyTargetHours: 8,
    priority: 'High',
    description: 'Solving standard DSA 450 sheet, LeetCode mediums, system design basics, and mock interviews.',
    category: 'Placement',
  },
  {
    id: 'g-3',
    title: 'System Design & Modern Python',
    targetDate: '2026-11-30',
    weeklyTargetHours: 4,
    priority: 'Medium',
    description: 'Deep dive into asynchronous Python, FastAPI microservices, and distributed systems architecture.',
    category: 'Personal',
  },
  {
    id: 'g-4',
    title: 'Build Distributed File System Project',
    targetDate: '2026-12-20',
    weeklyTargetHours: 5,
    priority: 'Medium',
    description: 'Hands-on practical implementation applying OS concepts (concurrency, sockets, raft consensus).',
    category: 'Project',
  },
];

export const INITIAL_WEEKLY_TARGETS: WeeklyTarget[] = [
  {
    id: 'wt-1',
    goalId: 'g-1',
    title: 'Finish COA Module 2 (Cache Memory & Pipelining)',
    targetHours: 4,
    completedHours: 3,
    weekStartDate: '2026-09-14',
    subtasks: [
      { id: 'st-1', title: 'Review Direct & Set-Associative Cache mapping formulas', completed: true },
      { id: 'st-2', title: 'Solve 10 previous year GATE questions on Cache miss penalty', completed: true },
      { id: 'st-3', title: 'Draw 5-stage RISC pipeline execution diagram', completed: true },
      { id: 'st-4', title: 'Summarize Data hazards & Branch prediction notes', completed: false },
    ],
  },
  {
    id: 'wt-2',
    goalId: 'g-2',
    title: 'Complete 25 DSA Problems (Binary Search & Trees)',
    targetHours: 6,
    completedHours: 4.5,
    weekStartDate: '2026-09-14',
    subtasks: [
      { id: 'st-5', title: 'Solve 5 Binary Search on answer space problems', completed: true },
      { id: 'st-6', title: 'Implement Binary Tree BFS & DFS traversals from scratch', completed: true },
      { id: 'st-7', title: 'Solve LeetCode #102, #104, #236 (LCA in Tree)', completed: false },
      { id: 'st-8', title: 'Practice Diameter and Maximum Path Sum in Trees', completed: false },
    ],
  },
  {
    id: 'wt-3',
    title: 'Operating Systems Assignment 2 (Process Sync)',
    targetHours: 3,
    completedHours: 2,
    weekStartDate: '2026-09-14',
    subtasks: [
      { id: 'st-9', title: 'Implement Producer-Consumer problem using POSIX Semaphores in C', completed: true },
      { id: 'st-10', title: 'Write report on Peterson solution proof of mutual exclusion', completed: false },
    ],
  },
  {
    id: 'wt-4',
    goalId: 'g-1',
    title: 'GATE Engg Math: Linear Algebra Matrix Rank',
    targetHours: 3,
    completedHours: 1.5,
    weekStartDate: '2026-09-14',
    subtasks: [
      { id: 'st-11', title: 'Watch Lecture on Row Echelon form & Null space', completed: true },
      { id: 'st-12', title: 'Solve 15 GATE questions on Eigenvalues & Cayley-Hamilton theorem', completed: false },
    ],
  },
];

export const INITIAL_DAILY_TASKS: DailyTask[] = [
  // Friday Sep 18, 2026 (Today)
  {
    id: 'dt-1',
    title: 'COA — Cache Memory notes & practice questions',
    date: '2026-09-18',
    startTime: '18:00',
    endTime: '18:45',
    durationMinutes: 45,
    category: 'COA',
    goalId: 'g-1',
    notes: 'Covered Direct mapped cache hit/miss ratio calculation.',
    completed: true,
  },
  {
    id: 'dt-2',
    title: 'DSA — Trees Traversal (LeetCode #102 & #236)',
    date: '2026-09-18',
    startTime: '19:30',
    endTime: '20:30',
    durationMinutes: 60,
    category: 'DSA',
    goalId: 'g-2',
    notes: 'Level order traversal queue method + LCA recursion.',
    completed: false,
  },
  {
    id: 'dt-3',
    title: 'OS — Mutex Locks & Semaphores recap',
    date: '2026-09-18',
    startTime: '21:15',
    endTime: '22:00',
    durationMinutes: 45,
    category: 'OS',
    notes: 'Double check boundary conditions in POSIX sem_wait.',
    completed: false,
  },
  {
    id: 'dt-4',
    title: 'Weekly Revision & Formula Sheet Update',
    date: '2026-09-18',
    startTime: '22:15',
    endTime: '22:45',
    durationMinutes: 30,
    category: 'GATE',
    goalId: 'g-1',
    notes: 'Add COA formulas into the summary notebook.',
    completed: false,
  },

  // Saturday Sep 19, 2026 (Live Current Date)
  {
    id: 'dt-5',
    title: 'GATE Math: Eigenvalues & Matrix Rank problem set',
    date: '2026-09-19',
    startTime: '08:30',
    endTime: '09:45',
    durationMinutes: 75,
    category: 'GATE',
    goalId: 'g-1',
    notes: 'Solve 15 GATE questions on Eigenvalues & Cayley-Hamilton theorem.',
    completed: true,
    actualMinutes: 75,
  },
  {
    id: 'dt-6',
    title: 'COA — Pipelining Hazards & Cache Performance review',
    date: '2026-09-19',
    startTime: '14:00',
    endTime: '15:15',
    durationMinutes: 75,
    actualMinutes: 60,
    category: 'COA',
    goalId: 'g-1',
    notes: 'Structural, data, and control hazard branch prediction analysis.',
    completed: true,
  },
  {
    id: 'dt-7',
    title: 'DSA — LeetCode Weekly Contest Practice (Trees & DP)',
    date: '2026-09-19',
    startTime: '16:00',
    endTime: '17:30',
    durationMinutes: 90,
    actualMinutes: 90,
    category: 'Placement',
    goalId: 'g-2',
    notes: 'Solve LeetCode #102, #104, #236 (LCA in Tree).',
    completed: false,
  },
  {
    id: 'dt-8',
    title: 'Operating Systems Lab — POSIX Semaphores Finalization',
    date: '2026-09-19',
    startTime: '18:45',
    endTime: '20:00',
    durationMinutes: 75,
    category: 'OS',
    notes: 'Implement Producer-Consumer problem using POSIX Semaphores in C.',
    completed: false,
  },
  {
    id: 'dt-9',
    title: 'Weekly Engineering Goal Review & Formula Sheet Update',
    date: '2026-09-19',
    startTime: '21:15',
    endTime: '22:00',
    durationMinutes: 45,
    category: 'GATE',
    goalId: 'g-1',
    notes: 'Consolidate week 5 formulas into physical engineering log.',
    completed: false,
  },
];

export const INITIAL_FREE_TIME_ALLOCATIONS: FreeTimeAllocation[] = [
  {
    id: 'fta-1',
    title: 'GATE Preparation (COA & Discrete Math)',
    activityCategory: 'GATE',
    date: '2026-09-19',
    startTime: '10:00',
    endTime: '12:30',
    plannedMinutes: 150,
    actualMinutes: 150,
    color: '#4f46e5', // indigo
    notes: 'Solve PYQs and revise memory hierarchy formulas.',
    completed: true,
  },
  {
    id: 'fta-2',
    title: 'Placement Practice (Mock Tests & Core CS)',
    activityCategory: 'Placement',
    date: '2026-09-19',
    startTime: '15:30',
    endTime: '17:00',
    plannedMinutes: 90,
    actualMinutes: 90,
    color: '#0891b2', // cyan
    notes: 'Online assessment simulation & timed problem solving.',
    completed: true,
  },
  {
    id: 'fta-3',
    title: 'Distributed System Project Sprint',
    activityCategory: 'Project',
    date: '2026-09-19',
    startTime: '20:00',
    endTime: '21:15',
    plannedMinutes: 75,
    actualMinutes: 45,
    color: '#059669', // emerald
    notes: 'Raft consensus heartbeat RPC implementation.',
    completed: false,
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [];

